# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4750eee5937b97038022b548a5e9cf4c7714cbea6670e8d3e9b034164aea7198f78d600fdb653cf0456c377fdc7b6c8ddacd4209d9a9960a9134dcb8e550cb6

test:
  secret_key_base: 5586615b32d3250e53aa8efca8458357f4baae2f2888b2afa0715b83de5a6ec375bedd076e2758a9c554f36756ac21c9db7cf179c805b4ff2791073c0206011f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
