# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4199d247dbef734c671c9bdc699472fef60b57f6e874cc2ccee2a67d6a2dff650e4cb0483ea3d24f9233195b75421b21ae053337ad5aeccc13bcb12634f61aa

test:
  secret_key_base: 28a3fef4594421c6e21cd96c51c69a3bda8e483c6014ce2be07ea0264940bf53410138dec33c19c1fc551848b4c4b9ad7c800c8840d9476914cbf5510b5f4a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
